dist: focal

language: python
python:
  - "3.6"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
      - libtcmalloc-minimal4

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.20.0/bazel_0.20.0-linux-x86_64.deb
  - sha256sum -c tools/bazel_0.20.0-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_0.20.0-linux-x86_64.deb

install:
  - python -m pip install --upgrade pip setuptools
  - pip install -r requirements.txt

env:
  - LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4"

before_script:
  - pip install flake8
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics

script:
  - tools/travis_tests.sh
